// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: libnet/protobuf/rpc.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared between all protocols
type MessageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageID     string                 `protobuf:"bytes,3,opt,name=messageID,proto3" json:"messageID,omitempty"`
	SenderID      string                 `protobuf:"bytes,4,opt,name=senderID,proto3" json:"senderID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	mi := &file_libnet_protobuf_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_libnet_protobuf_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_libnet_protobuf_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *MessageData) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *MessageData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageData) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *MessageData) GetSenderID() string {
	if x != nil {
		return x.SenderID
	}
	return ""
}

type HeaderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PreviousHash  []byte                 `protobuf:"bytes,2,opt,name=previousHash,proto3" json:"previousHash,omitempty"`
	Height        uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce         uint64                 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	MerkleRoot    []byte                 `protobuf:"bytes,6,opt,name=merkleRoot,proto3" json:"merkleRoot,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,7,opt,name=stateRoot,proto3" json:"stateRoot,omitempty"`
	Bits          uint32                 `protobuf:"varint,8,opt,name=bits,proto3" json:"bits,omitempty"`
	TotalWork     string                 `protobuf:"bytes,9,opt,name=totalWork,proto3" json:"totalWork,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,10,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,11,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	Beneficiary   []byte                 `protobuf:"bytes,12,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderData) Reset() {
	*x = HeaderData{}
	mi := &file_libnet_protobuf_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderData) ProtoMessage() {}

func (x *HeaderData) ProtoReflect() protoreflect.Message {
	mi := &file_libnet_protobuf_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderData.ProtoReflect.Descriptor instead.
func (*HeaderData) Descriptor() ([]byte, []int) {
	return file_libnet_protobuf_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *HeaderData) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HeaderData) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

func (x *HeaderData) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *HeaderData) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeaderData) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *HeaderData) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *HeaderData) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *HeaderData) GetBits() uint32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *HeaderData) GetTotalWork() string {
	if x != nil {
		return x.TotalWork
	}
	return ""
}

func (x *HeaderData) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *HeaderData) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *HeaderData) GetBeneficiary() []byte {
	if x != nil {
		return x.Beneficiary
	}
	return nil
}

type HeadersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageData   *MessageData           `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	Hashes        [][]byte               `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersRequest) Reset() {
	*x = HeadersRequest{}
	mi := &file_libnet_protobuf_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersRequest) ProtoMessage() {}

func (x *HeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libnet_protobuf_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersRequest.ProtoReflect.Descriptor instead.
func (*HeadersRequest) Descriptor() ([]byte, []int) {
	return file_libnet_protobuf_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *HeadersRequest) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *HeadersRequest) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type HeadersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageData   *MessageData           `protobuf:"bytes,1,opt,name=messageData,proto3" json:"messageData,omitempty"`
	HeaderData    []*HeaderData          `protobuf:"bytes,2,rep,name=headerData,proto3" json:"headerData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadersResponse) Reset() {
	*x = HeadersResponse{}
	mi := &file_libnet_protobuf_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadersResponse) ProtoMessage() {}

func (x *HeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libnet_protobuf_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadersResponse.ProtoReflect.Descriptor instead.
func (*HeadersResponse) Descriptor() ([]byte, []int) {
	return file_libnet_protobuf_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *HeadersResponse) GetMessageData() *MessageData {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *HeadersResponse) GetHeaderData() []*HeaderData {
	if x != nil {
		return x.HeaderData
	}
	return nil
}

var File_libnet_protobuf_rpc_proto protoreflect.FileDescriptor

const file_libnet_protobuf_rpc_proto_rawDesc = "" +
	"\n" +
	"\x19libnet/protobuf/rpc.proto\x12\x13protocols.rpcprotos\"\x8b\x01\n" +
	"\vMessageData\x12$\n" +
	"\rclientVersion\x18\x01 \x01(\tR\rclientVersion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x1c\n" +
	"\tmessageID\x18\x03 \x01(\tR\tmessageID\x12\x1a\n" +
	"\bsenderID\x18\x04 \x01(\tR\bsenderID\"\xde\x02\n" +
	"\n" +
	"HeaderData\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\"\n" +
	"\fpreviousHash\x18\x02 \x01(\fR\fpreviousHash\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12\x1e\n" +
	"\n" +
	"merkleRoot\x18\x06 \x01(\fR\n" +
	"merkleRoot\x12\x1c\n" +
	"\tstateRoot\x18\a \x01(\fR\tstateRoot\x12\x12\n" +
	"\x04bits\x18\b \x01(\rR\x04bits\x12\x1c\n" +
	"\ttotalWork\x18\t \x01(\tR\ttotalWork\x12\x1a\n" +
	"\bgasLimit\x18\n" +
	" \x01(\x04R\bgasLimit\x12\x18\n" +
	"\agasUsed\x18\v \x01(\x04R\agasUsed\x12 \n" +
	"\vbeneficiary\x18\f \x01(\fR\vbeneficiary\"l\n" +
	"\x0eHeadersRequest\x12B\n" +
	"\vmessageData\x18\x01 \x01(\v2 .protocols.rpcprotos.MessageDataR\vmessageData\x12\x16\n" +
	"\x06hashes\x18\x02 \x03(\fR\x06hashes\"\x96\x01\n" +
	"\x0fHeadersResponse\x12B\n" +
	"\vmessageData\x18\x01 \x01(\v2 .protocols.rpcprotos.MessageDataR\vmessageData\x12?\n" +
	"\n" +
	"headerData\x18\x02 \x03(\v2\x1f.protocols.rpcprotos.HeaderDataR\n" +
	"headerDataB!Z\x1faugust/libnet/protobuf;protobufb\x06proto3"

var (
	file_libnet_protobuf_rpc_proto_rawDescOnce sync.Once
	file_libnet_protobuf_rpc_proto_rawDescData []byte
)

func file_libnet_protobuf_rpc_proto_rawDescGZIP() []byte {
	file_libnet_protobuf_rpc_proto_rawDescOnce.Do(func() {
		file_libnet_protobuf_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libnet_protobuf_rpc_proto_rawDesc), len(file_libnet_protobuf_rpc_proto_rawDesc)))
	})
	return file_libnet_protobuf_rpc_proto_rawDescData
}

var file_libnet_protobuf_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_libnet_protobuf_rpc_proto_goTypes = []any{
	(*MessageData)(nil),     // 0: protocols.rpcprotos.MessageData
	(*HeaderData)(nil),      // 1: protocols.rpcprotos.HeaderData
	(*HeadersRequest)(nil),  // 2: protocols.rpcprotos.HeadersRequest
	(*HeadersResponse)(nil), // 3: protocols.rpcprotos.HeadersResponse
}
var file_libnet_protobuf_rpc_proto_depIdxs = []int32{
	0, // 0: protocols.rpcprotos.HeadersRequest.messageData:type_name -> protocols.rpcprotos.MessageData
	0, // 1: protocols.rpcprotos.HeadersResponse.messageData:type_name -> protocols.rpcprotos.MessageData
	1, // 2: protocols.rpcprotos.HeadersResponse.headerData:type_name -> protocols.rpcprotos.HeaderData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_libnet_protobuf_rpc_proto_init() }
func file_libnet_protobuf_rpc_proto_init() {
	if File_libnet_protobuf_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libnet_protobuf_rpc_proto_rawDesc), len(file_libnet_protobuf_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libnet_protobuf_rpc_proto_goTypes,
		DependencyIndexes: file_libnet_protobuf_rpc_proto_depIdxs,
		MessageInfos:      file_libnet_protobuf_rpc_proto_msgTypes,
	}.Build()
	File_libnet_protobuf_rpc_proto = out.File
	file_libnet_protobuf_rpc_proto_goTypes = nil
	file_libnet_protobuf_rpc_proto_depIdxs = nil
}
