
syntax = "proto3";

package protocols.rpcprotos;

// This line tells protoc where to put the Go code and what package to use
option go_package = "august/libnet/protobuf;protobuf";

// Shared between all protocols
message MessageData {
  string clientVersion = 1;
  uint64 timestamp = 2;
  string messageID = 3;
  string senderID = 4;
}

message HeaderData {
  uint64 version = 1;
  bytes previousHash = 2;
  uint64 height = 3;
  uint64 timestamp = 4;
  uint64 nonce = 5;
  bytes merkleRoot = 6;
  bytes stateRoot = 7;
  uint32 bits = 8;
  string totalWork = 9;
  uint64 gasLimit = 10;
  uint64 gasUsed = 11;
  bytes beneficiary = 12;
}

message HeadersRequest {
  MessageData messageData = 1;
  repeated bytes hashes = 2;
}

message HeadersResponse {
  MessageData messageData = 1;
  repeated HeaderData headerData = 2;
}

message InstructionData{
  bytes opcode = 1; // Actually a uint8
  bytes value = 2; // types/types.go::Instruction  Value is actually a string representing a hex
                   // value, we send it as bytes here
} 

message TransactionData{
  bytes frompk = 1;
  bytes topk = 2;
  uint64 amount = 3;
  bytes signature = 4;
  uint64 nonce=  5;
  uint64 timestamp = 6;
  uint64 chainid = 7;
  repeated InstructionData callInstructions =8;
  repeated InstructionData initInstructions=9;
  uint64 gasLimit=10;
  uint64 gasPrice=11;
  bytes data=12;
}

message BlockData{
  HeaderData header = 1; 
  repeated TransactionData transactions = 2;
  
}
message BlocksRequest{
  MessageData messageData = 1;
  repeated bytes hashes = 2;
}
message BlocksResponse{
  MessageData messageData = 1;
  repeated BlockData blockData = 2;
}

