package main

import (
	"august/avm"
	"august/marigold"
	"august/types"
	"fmt"
	"math/big"
)

func main() {
	// Simple contract with init and call functions
	code := `
	define init() : int{
		emit(1)
		return 42 + 2
	}

	define call(x: int) : int{
		emit(x + 10)
		return x
	}
	`

	fmt.Println("Compiling contract:")
	fmt.Println(code)

	// Parse the code
	tokens, err := marigold.Lex(code)
	if err != nil {
		fmt.Printf("Lex error: %v\n", err)
		return
	}

	ast, err := marigold.Parse(tokens)
	if err != nil {
		fmt.Printf("Parse error: %v\n", err)
		return
	}

	// Generate bytecode using Codegen which adds entry points
	ctx := marigold.CodegenWithContext(ast)

	// Convert instructions to string format for display
	var bytecode string
	for _, inst := range ctx.Instructions {
		if inst.Opcode == types.PUSH && inst.Value != nil {
			bytecode += "PUSH " + *inst.Value + " "
		} else {
			bytecode += inst.Opcode.String() + " "
		}
	}

	fmt.Printf("\nGenerated bytecode:\n%s\n", bytecode)

	fmt.Printf("\nFunction addresses:\n")
	for name, addr := range ctx.FunctionIndex {
		fmt.Printf("  %s: %d\n", name, addr)
	}

	// Test deployment (init)
	// Convention: IC=0 jumps to init
	fmt.Printf("\n=== DEPLOYMENT: Executing init() ===\n")
	deployRuntime := avm.NewTestRuntime(1000000, ctx.Instructions)
	deployRuntime.FramePointer = 0
	deployRuntime.IC = 0 // Start at entry point 0 (init)

	// Execute until we return
	for deployRuntime.IC >= 0 && deployRuntime.IC < len(deployRuntime.Instructions) {
		err := deployRuntime.ExecuteInstruction()
		if err != nil {
			fmt.Printf("Error: %v\n", err)
			break
		}
	}

	if deployRuntime.Stack.Size() > 0 {
		result, _ := deployRuntime.Stack.Top()
		fmt.Printf("Deployment complete. init() returned: %d\n", result)
	}

	// Test contract call
	// Convention: IC=2 jumps to call (IC=0,1 is init entry, IC=2,3 is call entry)
	fmt.Printf("\n=== CONTRACT CALL: Executing call(5) ===\n")
	callRuntime := avm.NewTestRuntime(1000000, ctx.Instructions)
	// Set up argument
	callRuntime.Stack.Push(big.NewInt(5)) // argument x -> Stack[0]
	callRuntime.FramePointer = 0          // Frame pointer at start of args
	callRuntime.IC = 2                    // Start at entry point 2 (call)

	// Execute until we return
	for callRuntime.IC >= 0 && callRuntime.IC < len(callRuntime.Instructions) {
		err := callRuntime.ExecuteInstruction()
		if err != nil {
			if err == avm.ErrProgramStopped {
				break
			}
			fmt.Printf("Error: %v\n", err)
			break
		}
	}

	if callRuntime.Stack.Size() > 0 {
		result, _ := callRuntime.Stack.Top()
		fmt.Printf("Contract call complete. call(5) returned: %d\n", result)
	}
}
